name: AMP GUIMARAES
description: Aqui entra uma desc do que esse AMP eh capaz de fazer
author: Jose Guimaraes
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-30"

environment_variables:
  RANDOM_VARIABLE_NAME:
    default: "DEFAULT-VALUE"
    description: "A description providing user clarifying information about the variable."
    required: false

runtimes:
  - editor: JupyterLab ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.10 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:
  ## JOB related AMP snippet
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: 0_session-install-dependencies/install-dependencies.py
    arguments: None
    short_summary: Install dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_deps
    short_summary: Running install dependencies job.
    cpu: 1
    memory: 2
